os: linux
dist: xenial
services: docker
language: minimal
install: skip
script: "./dist/travis/travis-ci.sh"

# For each linux build, a different job/instance (with the constraints
# above) is executed in parallel in stage 'test'.
env:
  matrix:
    - IMAGE=stretch+mcode
    - IMAGE=stretch+mcode+gpl
#    - IMAGE=buster+mcode
#    - IMAGE=buster+mcode+gpl
    - IMAGE=ubuntu14+mcode
    - IMAGE=ubuntu14+llvm-3.8
#    - IMAGE=ubuntu18+mcode
#    - IMAGE=ubuntu18+llvm-5.0
    - IMAGE=fedora28+mcode
    - IMAGE=fedora28+llvm

deploy:
  - &deploy-docker
    provider: releases
    skip_cleanup: true
    api_key:
      secure: ji6LXOmD5V2N+ELHZr4oJsmxPhedk+8W6jfCqQdEbewQ42N+fKOq3lgqJni7ZdfpZaulB9OHPTApv3bwOjXjtN9rfBGmq//U9CwvzHmUeomdQv6WQOVevaWSXl3DNL9fk3yKynyFrsv4pvr45L8GIjaHLggKcYhNFPJ2rrnJlDoFT9MqQNpmP7Bg/LnwVQiv+ZDPkLlMWQzrXzLamdQILARPQka+kCdXl/sHH6OKvLgRvu9yvyXYSSfbyAHP+THISS5gDciizSBeWGlU75kgj/N+mkV+8NvtTTfEIgG8y49WJz6aBooTmRzk/jZW1dKMbDR6c5bpTmRvMZSzeSBuAR6WLhr6HevgCPi/1fX1y3pkVSrgBUF5KcxPgWCZp0I05QjaJOdvQDl1hH4TlVwpT18lM2+cWrui9fS7spnk/AuNKX882C5QWWRy28lIPasCVnwfeKX8a9KAwY9OqVOenoLC1yx7NJOGfH1bjuSYYxyR4XgLiGTHKALAuknCyD9QL0o378IwqxHMcsN0Gsd+GndMu0/b8GvSqfzDpV1XknqabQFwkZLs+Yydw0snfBUzXw9TfOk78IiPYEgXAxsQKBAkK7qvO36HIxLlSQXglXU1D4IDtQYDUel6vKll4pgu0WMxStQCbj51yDVJKvRhzwiBNC6Pwgzt2JTrpwM/T/U=
    file: "ghdl-*.tgz"
    file_glob: true
    on:
      repo: ghdl/ghdl
      all_branches: true
      tags: true

jobs:
  include:
    # One additional job is described in stage 'test' for the macos build.
    # The constraints above are used, except explicitly overriden.
    - &osx
      os: osx
      language: c
      osx_image: xcode9.4
      install: true
      cache:
        directories:
          - gnat
      env: IMAGE=macosx+mcode
    # Optionally, more macos jobs can be added. See list of available versions at https://docs.travis-ci.com/user/reference/osx/#macos-version
#   - <<: *osx
#     osx_image: xcode10
    - env: IMAGE=man
      script: ./dist/travis/man.sh
      deploy:
        - <<: *deploy-docker
          file: "doc/_build/man/ghdl.1"
    - env: IMAGE=doc
      language: python
      python: '3.6'
      before_script:
        - git fetch --unshallow --tags
        - pip3 install -r doc/requirements.txt
      script: python3 doc/build.py
      after_success: ./doc/update_site.sh
      deploy:
        provider: pages
        repo: 1138-4EB/ghdl
        target_branch: gh-pages
        local_dir: doc/_site
        github_token: $GITHUB_PAGES_TOKEN
        skip_cleanup: true
        on:
          all_branches: true
