name: 'doc'
on: [push, pull_request]
env:
  CI: true
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./doc/make.sh
      env:
        GH_DEPKEY: ${{ secrets.GH_DEPKEY }}
        GH_SHA:    ${{ github.sha }}
